spring.application.name=ControlHabitos
spring.datasource.url=jdbc:sqlserver://TU BASE DE DATOS;databaseName=ControlHabitosDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=TU USUARIO
spring.datasource.password=TU CONTRASEÑA
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración de JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
